### PR TITLE
Fix mozilla dropdown

### PR DESCRIPTION
**Pull request by lennerd**
Okay, I think I found a solution for the display bugs in Firefox. It all was connected to strange behaviors when using `float`. Please check if this works for you, too.

The process now would be to rebase your branch to the current master, so that you can add this PR to your `UI` branch. And then we can merge it into the wheelmap, finally.

### CODE REVIEW

**Comment by yeralin** [comment]
so, what should I do?

**Comment by lennerd** [comment]
You need to rebase your UI branch to the current master of sozialhelden/wheelmap, so that the first commit `Add mallorca region` from @christoph-buente is not part of this PR anymore.

Than you can merge this PR into your UI branch, so we can merge your PR in our branch if everything is working fine.

I do this complicated process because I would like you to test this changes with your system (maybe also with IE) so we are sure to fix this bug.

If you think, that you are not able to make all this properly we can just make push this into our sozialhelden/wheelmap repository. How you like. :wink:

**Comment by yeralin** [comment]
Ok check it out. Rebased

**Comment by lennerd** [comment]
Okay, I needed to remove the conflicts. You should be able to merge this into your UI branch now. Please review the changes I made. Does this work in your browsers?

**Pull request merged**
